apiVersion: apps/v1
kind: Deployment
metadata:
  name: starttech-backend-api
  labels:
    app: starttech-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starttech-backend-api
  template:
    metadata:
      labels:
        app: starttech-backend-api
    spec:
      containers:
        - name: backend
          image: PLACEHOLDER_ECR_IMAGE_URI
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: starttech-backend-secrets
                  key: redis-endpoint
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: starttech-backend-secrets
                  key: mongodb-uri
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
